### ISSUE TITLE
Your version of gopls appears to be out of date.

### ISSUE THREAD

**Issue by RicardoNiepel** [microsoft/vscode-remote-try-go#12]
With this devcontainer I always get the message "Your version of gopls appears to be out of date. Please update for an improved experience."

Would be great if the Dockerfile can already take care of this.

**Comment by holms** [comment]
And no reaction this yet?   :(

**Comment by Chuxel** [comment]
The Dockerfile will contain a version of gopls. If the image gets reused because of caching, this can happen. I've also seen this happen if it is installed under pkgs from a previous run.  A fresh image will not exhibit this behavior.

**Comment by Chuxel** [comment]
@hyangah Any thoughts on how we could reduce how often this situation happens?

**Comment by hyangah** [comment]
`"go.useGoProxyToCheckForToolUpdates": false` maybe?

**Comment by Chuxel** [comment]
That looks like it will work. I'll do a PR here with the latest definition.

**Comment by Chuxel** [comment]
Hopefully the setting above resolves how often this is seen. Closing for now.
