### ISSUE TITLE
Docker image build fails during "go get" (gopls)

### ISSUE THREAD

**Issue by fishnux** [microsoft/vscode-remote-try-go#21]
The whole "go get" command inside Dockerfile returns a non-zero error code, causing the image build to fail. 
I've isolated the failure to the package "gopls":
```The command '/bin/sh -c go get -u -v golang.org/x/tools/cmd/gopls' returned a non-zero code: 1```

**Comment by Chuxel** [comment]
This was resolved, but we neglected to close the issue.
