### ISSUE TITLE
Remote Containers: Try a Sample is not shown

### ISSUE THREAD

**Issue by BXK20** [microsoft/vscode-remote-try-go#27]
On Pressing F1, I do not see Try a Sample as a option. I see several other Remote Container options as shown in the attached snippet
![image](https://user-images.githubusercontent.com/64117274/88172065-6677be80-cbee-11ea-884a-0b38cf92d138.png)
![image](https://user-images.githubusercontent.com/64117274/88172429-f7e73080-cbee-11ea-9344-c817f9367d4e.png)

Please advise.
Thanks

**Comment by Chuxel** [comment]
@BXK20 It looks like you are in a WSL window, is that correct?  If so, go to a normal window and you should see it.

**Comment by BXK20** [comment]
Yes. That was the case. Thanks for your immediate response and help.

**Comment by Chuxel** [comment]
Great! Closing issue.
