### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by kgoedert** [microsoft/vscode-remote-try-go#8]
Hi,

I just downloaded the example, if I try the command `go build`, I get this error
```
vscode@bd277fa5c94e:/workspaces/vscode-remote-try-go/src/main$ go build 
server.go:10:2: cannot find package "hello" in any of:
        /usr/local/go/src/hello (from $GOROOT)
        /go/src/hello (from $GOPATH)
```
How can I set the GOPATH properly?

**Comment by Chuxel** [comment]
@kgoedert This is using the go.inferGopath option in the extension.  You can build and run just by hitting F5.

More details on what this is doing here:
https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension#gopath-from-goinfergopath-setting
