### ISSUE TITLE
Go fmt and autocomplete imports

### ISSUE THREAD

**Issue by prugala** [microsoft/vscode-remote-try-go#9]
Hello

I have a problems with go fmt and autocomplete imports on file save. When Im using go extension  without docker and remote container all works and when write code (example):

```
fmt.Println("test")
       fmt.Println("test")```

on save lint fix it and import for fmt is adding.

With remote container and docker (I used your repo on test) lint and import autocomplete don't work. Ofc I installed also all tools for go extension. When I write `go fmt server.go` lint fixes code.

**Comment by Chuxel** [comment]
@prugala Are you still seeing this behavior?

**Comment by prugala** [comment]
Hi @Chuxel atm, I don't use VSC with remote go plugin so I can't confirm it. 
I'm closing the issue, if someone else will have the same issue on the current version will open new one.
